#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="st -e vim"
# DMENUEDITOR="st -e nvim"
DMEDITOR="alacritty -e vim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
"alacritty - $HOME/.alacritty.yml"
"bash - $HOME/.bashrc"
"starship - $HOME/.config/starship.toml"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"dunst - $HOME/.config/dunst/dunstrc"
"fish - $HOME/.config/fish/config.fish"
"herbstluftwm - $HOME/.config/herbstluftwm/autostart"
"picom - $HOME/.config/picom/picom.conf"
"polybar - $HOME/.config/polybar/forest/config.ini"
"qutebrowser - $HOME/.config/qutebrowser/autoconfig.yml"
"surf - $HOME/surf-distrotube/config.def.h"
"sxhkd - $HOME/.config/sxhkd/sxhkdrc"
"tabbed - $HOME/tabbed-distrotube/config.def.h"
"vifm - $HOME/.config/vifm/vifmrc"
"vim - $HOME/.vimrc"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 30 -p 'Edit config:')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi

